defaults:
  - _self_
  - data: iam
  - loader: eval_ctc
  - preprocess: default
  - model: vt_ctc
  - decode: beam
  - span_mask: vt
  - mlflow: local

eval:
  device: cuda
  split: test
  checkpoint_path: runs/htr_vt_ctc/best.pt