defaults:
  - _self_
  - data: iam
  - preprocess: default
  - augment: paper
  - loader: default
  - mlflow: local

command:
  name: inspect_augmentations

inspect_aug:
  index: 37
  n: 19
  cols: 2
  seed: 123
  out_dir: data/augmentations
