seed: 42
deterministic: true
device: cuda

epochs: 100
lr: 3e-4

weight_decay: 1e-5
adam_beta1: 0.9
adam_beta2: 0.999
adam_eps: 1e-8

grad_clip: 5.0

early_stop:
  patience: 100

runs_dir: runs/crnn_ctc

# Сделается сам после трейна
vocab_path: ${data.processed_dir}/vocab_ctc.json

log_checkpoint_to_mlflow: true
