device: cuda

optimizer:
  name: adamw
  lr: 1e-5
  weight_decay: 0.0001
  betas: [0.9, 0.999]
  eps: 1.0e-08

scheduler:
  name: cosine   # none | linear | cosine
  warmup_ratio: 0

max_epochs: 100
patience: 100
runs_dir: runs

amp: true
grad_accum_steps: 1
max_grad_norm: 5.0

log_checkpoint_to_mlflow: true
log_last_checkpoint_to_mlflow: false
